WebSuperZapatos/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebSuperZapatos.App_Start;
using WebSuperZapatos.Models;

namespace WebSuperZapatos.Controllers
{
    public class ArticlesController : Controller
    {
        private ApplicationDbContext _context = new ApplicationDbContext();

        // GET: Articles

        public async Task<ActionResult> Index()
        {
            var articles = await _context.Articles.Include(x => x.Stores).ToListAsync();

            return View(articles);
        }

        public ActionResult Create()
        {
            ViewBag.StoreID = new SelectList(_context.Stores, "StoreID", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create( Articles articles)
        {
            if (ModelState.IsValid)
            {
                _context.Articles.Add(articles);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.StoreID = new SelectList(_context.Stores, "StoreID", "Name", articles.StoreID);
            return View(articles);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articles articles = await _context.Articles.FindAsync(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            ViewBag.StoreID = new SelectList(_context.Stores, "StoreID", "Name", articles.StoreID);
            return View(articles);
        }

   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit( Articles articles)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(articles).State = EntityState.Modified;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.StoreID = new SelectList(_context.Stores, "StoreID", "Name", articles.StoreID);
            return View(articles);
        }

     

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articles articles = await _context.Articles.FindAsync(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            return View(articles);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(int? id)
        {
            Articles articles = await _context.Articles.FindAsync(id);
            _context.Articles.Remove(articles);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

WebSuperZapatos/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebSuperZapatos.App_Start;
using WebSuperZapatos.Models;

namespace WebSuperZapatos.Controllers
{
    public class StoresController : Controller
    {
        private  ApplicationDbContext _context = new ApplicationDbContext();
        
       
        // GET: Stores
        public async Task<ActionResult> Index()
        {
            var List = await _context.Stores.ToListAsync();

            return View(List);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Stores stores)
        {
            if (ModelState.IsValid)
            {
                _context.Stores.Add(stores);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(stores);
        }
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stores stores = await _context.Stores.FindAsync(id);
            if (stores == null)
            {
                return HttpNotFound();
            }
            return View(stores);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Stores stores)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(stores).State = EntityState.Modified;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(stores);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(int? id)
        {
            Stores stores = await _context.Stores.FindAsync(id);
            _context.Stores.Remove(stores);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
           
        }

      
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebSuperZapatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title  Super Zapatos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
</head>
<body>
  
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Super Zapatos</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Home")">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Stores")">Tiendas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Articles")">Articulos</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Servicio web
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a href="/services/StoresAPI/GetStores" target="_blank">GET: /services/StoresAPI/GetStores</a></li>
                            <li><a href="/services/ArticlesAPI/GetArticles" target="_blank">GET: /services/ArticlesAPI/GetArticles</a></li>
                            <li><a href="/services/ArticlesAPI/Stores/1" target="_blank">GET: /services/ArticlesAPI/Stores/1</a></li>
                        </ul>
                    </li>
                </ul>
                
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Web Super Zapatos</p>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
</body>
</html>